#!/usr/bin/env python
# coding=utf-8
# author: zengyuetian


# ! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Feb 28, 2018 11:37:21 AM


import sys
import os
from libs.common.path import TOOLS_PATH

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk

    py3 = 0
except ImportError:
    import tkinter.ttk as ttk

    py3 = 1


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def run(script):
    cmd = "python {0}".format(script)
    os.system(cmd)


def quit():
    exit(0)


def pull_meta():
    run(TOOLS_PATH + "/common/android_operation/file_op.py -a pull -f meta")


def push_meta():
    run(TOOLS_PATH + "/common/android_operation/file_op.py -a push -f meta")


def pull_conf():
    run(TOOLS_PATH + "/common/android_operation/file_op.py -a pull -f conf")


def push_conf():
    run(TOOLS_PATH + "/common/android_operation/file_op.py -a push -f conf")


def pull_data():
    run(TOOLS_PATH + "/common/android_operation/file_op.py -a pull -f data")


def push_data():
    run(TOOLS_PATH + "/common/android_operation/file_op.py -a push -f data")


def delete_conf():
    run(TOOLS_PATH + "/common/android_operation/file_op.py -a delete -f conf")


def delete_meta():
    run(TOOLS_PATH + "/common/android_operation/file_op.py -a delete -f meta")


def delete_data():
    run(TOOLS_PATH + "/common/android_operation/file_op.py -a delete -f data")


def install():
    print("start to install app")
    run(TOOLS_PATH + "/common/android_operation/app_op.py -a install")
    print("done")


def uninstall():
    print("start to uninstall app")
    run(TOOLS_PATH + "/common/android_operation/app_op.py -a uninstall")
    print("done")


def get():
    run(TOOLS_PATH + "/common/android_operation/get_devices.py")
    print("done")


def start():
    run(TOOLS_PATH + "/common/android_operation/app_op.py -a start")


def stop():
    run(TOOLS_PATH + "/common/android_operation/app_op.py -a stop")
